"""
GRAZING table builder.

It can:
1. run the GRAZING evaporation calculation if requested in the YAML,
2. collect the post-evaporation residue .dat files generated by GRAZING,
3. convert those .dat files into .csv tables for plotting,
4. read the relevant fort.* files mapped through fort.15,
5. build a recoil kernel, filter the populated cells, and reconstruct recoil angle and recoil energy-per-nucleon tables.

Usage:
----------
    python3 grazing_builder.py run-case --config <case>.yaml

Example:
    python3 grazing_builder.py run-case --config xe_pt_195Os.yaml

Should save following in YAML output_folder
-------------
<case_name>_tlf_all_rows.csv
    Post-evaporation residue rows from the generated .dat files.
<case_name>_tlf_summed.csv
    Summed post-evaporation cross sections in Z-N-A space.
<case_name>_kernel.csv
    Merged recoil kernel built from fort.* information.
<case_name>_kernel_filtered.csv
    Physically populated kernel cells for reconstruction.
<case_name>_reconstructed.csv
    Reconstructed recoil angle/energy.
"""
from __future__ import annotations

import argparse
import math
import re
import shutil
import subprocess
from pathlib import Path
from typing import Optional

import numpy as np
import pandas as pd
import yaml

AMU_MEV = 931.49410242

ELEMENT_Z = {
    "Hf": 72, "W": 74, "Ta": 73, "Os": 76, "Re": 75,
    "Pt": 78, "Ir": 77, "Xe": 54, "Au": 79, "Hg": 80, "Ba": 56,
}


def load_cfg(path: str | Path) -> dict:
    with open(path, "r", encoding="utf-8") as f:
        return yaml.safe_load(f)


def ensure_dir(path: Path) -> None:
    path.mkdir(parents=True, exist_ok=True)


def parse_target_label(target: str) -> tuple[int, str]:
    m = re.match(r"(\d+)([A-Za-z]+)", target)
    if not m:
        raise ValueError(f"Could not parse target label: {target}")
    return int(m.group(1)), m.group(2)


def choose_executable(base: Path, cfg: dict) -> str:
    exe_name = cfg.get("grazing_executable")
    if exe_name:
        if not (base / exe_name).exists():
            raise FileNotFoundError(f"Configured executable not found: {base / exe_name}")
        return exe_name
    for name in ["grazing_9_64bit", "grazing_9"]:
        if (base / name).exists():
            return name
    raise FileNotFoundError("Could not find grazing_9_64bit or grazing_9 in base_dir")


def read_fort15_mapping(path: Path) -> tuple[dict[str, str], Optional[int], Optional[int]]:
    txt = path.read_text(encoding="utf-8", errors="ignore").splitlines()
    mapping: dict[str, str] = {}
    delta_n: Optional[int] = None
    delta_z: Optional[int] = None

    for line in txt:
        s = line.strip()
        if not s:
            continue
        parts = s.split()
        if len(parts) < 2:
            continue

        key = parts[0].lower()
        if key == "edist":
            try:
                delta_n = int(parts[1])
            except Exception:
                pass

        tail = parts[-1]
        m = re.search(r"FOR0*([0-9]+)\.DAT", tail, flags=re.IGNORECASE)
        if m:
            mapping[key] = f"fort.{int(m.group(1))}"

    return mapping, delta_n, delta_z


def parse_block_samples(path: Path) -> pd.DataFrame:
    lines = path.read_text(encoding="utf-8", errors="ignore").splitlines()
    rows = []
    i = 0

    def num(s: str) -> float:
        return float(s.replace("D", "E").replace("d", "e"))

    while i < len(lines):
        s = lines[i].strip().lower()
        if s.startswith("r"):
            try:
                rvals = np.array([num(x) for x in lines[i].split()[1:]], dtype=float)
                thhdr = np.array([num(x) for x in lines[i + 1].split()[1:]], dtype=float)
                dsig = np.array([num(x) for x in lines[i + 2].split()[1:]], dtype=float)
            except Exception:
                i += 1
                continue

            i += 3
            while i < len(lines):
                row = lines[i].strip()
                low = row.lower()
                if not row or row.startswith("-"):
                    i += 1
                    continue
                if low.startswith("r") or low.startswith("distributions") or low.startswith("double differential"):
                    break
                parts = row.split()
                if len(parts) == len(rvals) + 1:
                    try:
                        x = num(parts[0])
                        vals = np.array([num(v) for v in parts[1:]], dtype=float)
                    except Exception:
                        i += 1
                        continue
                    for rr, th, ds, vv in zip(rvals, thhdr, dsig, vals):
                        rows.append({
                            "tkel_mev": x,
                            "r_fm": rr,
                            "theta_header_deg": th,
                            "dsig_rdl_header": ds,
                            "value": vv,
                        })
                i += 1
            continue
        i += 1

    if not rows:
        raise RuntimeError(f"No block data parsed from {path}")
    return pd.DataFrame(rows)


def make_lookup(df: pd.DataFrame) -> dict[tuple[float, float], dict]:
    out = {}
    for row in df.itertuples(index=False):
        out[(round(float(row.tkel_mev), 3), round(float(row.r_fm), 3))] = row._asdict()
    return out


def reconstruct_from_header(theta_header_deg: float, tkel_mev: float,
                            projectile_A: int, recoil_A: int, ejectile_A: int,
                            beam_energy_mevu: float,
                            branch: str = "larger") -> tuple[Optional[float], Optional[float]]:
    mp = projectile_A * AMU_MEV
    m1 = ejectile_A * AMU_MEV
    m2 = recoil_A * AMU_MEV

    Tproj_lab = projectile_A * beam_energy_mevu
    Tfinal_lab = Tproj_lab - tkel_mev
    if Tfinal_lab <= 0:
        return None, None

    p_in = math.sqrt(max(2.0 * mp * Tproj_lab, 0.0))
    th1 = math.radians(theta_header_deg)
    c1, s1 = math.cos(th1), math.sin(th1)

    a = (1.0 / m1) + (1.0 / m2)
    b = -2.0 * p_in * c1 / m2
    c = (p_in * p_in) / m2 - 2.0 * Tfinal_lab
    disc = b * b - 4.0 * a * c
    if disc < 0:
        return None, None

    roots = [(-b + math.sqrt(disc)) / (2.0 * a), (-b - math.sqrt(disc)) / (2.0 * a)]
    roots = [r for r in roots if r > 0]
    if not roots:
        return None, None

    sols = []
    for p1 in roots:
        p2x = p_in - p1 * c1
        p2y = -p1 * s1
        p2 = math.hypot(p2x, p2y)
        if p2 <= 0:
            continue
        theta2 = math.degrees(math.atan2(abs(p2y), p2x))
        T2 = p2 * p2 / (2.0 * m2)
        E2_per_u = T2 / recoil_A
        sols.append((theta2, E2_per_u))
    if not sols:
        return None, None
    sols = sorted(sols, key=lambda t: t[0])
    return sols[-1] if branch == "larger" else sols[0]


def run_evaporation(cfg: dict) -> Path:
    base = Path(cfg["base_dir"]).expanduser()
    auto_folder = Path(cfg["paths"]["auto_folder"]).expanduser()
    reaction = cfg["reaction"]
    proj = reaction["projectile"]
    targ = reaction["target"]
    A = targ["A"]
    sym = targ["symbol"]
    evap_kind = cfg.get("mode", {}).get("evap_kind", "tlf")
    run_dir = auto_folder / f"{A}{sym}_{evap_kind}_evap"

    # Remove any previous run folder so old .dat files do not cause Fortran overwrite errors.
    if run_dir.exists():
        shutil.rmtree(run_dir)
    ensure_dir(run_dir)

    exe_name = choose_executable(base, cfg)
    shutil.copy2(base / exe_name, run_dir / exe_name)
    shutil.copy2(base / "massexp_2004.dat", run_dir / "massexp_2004.dat")
    shutil.copy2(base / "mtablex_2004.dat", run_dir / "mtablex_2004.dat")

    # Interactive input passed to GRAZING for the evaporation run.
    input_tlf_evap = "\n".join([
        "OK",
        f"{proj['Z']} {proj['A']}",
        f"{targ['Z']} {targ['A']}",
        "c",
        "N",
        "both",
        "1",
        "no",
        "2",
        f"{reaction['ecm_mev']}",
        "no",
        "no",
        "4",
        "0",
        "0 0",
        "cm",
        "2",
        "2",
        "no",
        "no",
    ]) + "\n"

    proc = subprocess.run([f"./{exe_name}"], input=input_tlf_evap.encode("utf-8"), cwd=run_dir, capture_output=True)
    stdout_text = proc.stdout.decode("utf-8", errors="replace")
    stderr_text = proc.stderr.decode("utf-8", errors="replace")
    (run_dir / "run_stdout.txt").write_text(stdout_text, encoding="utf-8")
    (run_dir / "run_stderr.txt").write_text(stderr_text, encoding="utf-8")
    if proc.returncode != 0:
        raise RuntimeError(f"GRAZING evaporation failed in {run_dir}\n{stderr_text[-1500:]}")
    return run_dir


def build_afterevap_tables(base_dir: Path, target: str, out_rows: Path, out_summed: Path) -> tuple[pd.DataFrame, pd.DataFrame]:
    target_A, target_sym = parse_target_label(target)
    patterns = [
        f"**/*{target.lower()}*tlf_evap*/136Xe{target}_Z*_*.dat",
        f"**/*{target}*tlf_evap*/136Xe{target}_Z*_*.dat",
        f"**/*{target_sym.lower()}*tlf_evap*/136Xe{target}_Z*_*.dat",
        f"**/*{target_sym}*tlf_evap*/136Xe{target}_Z*_*.dat",
        f"**/136Xe{target}_Z*_*.dat",
    ]
    matches = []
    for p in patterns:
        matches.extend(base_dir.glob(p))
    matches = sorted(set(matches))
    if not matches:
        raise RuntimeError(f"No after-evaporation DAT files found under {base_dir} for target {target}")

    rows = []
    for fn in matches:
        m = re.search(r"_Z(\d+)_", fn.name)
        if not m:
            continue
        Z = int(m.group(1))

        # For W/Hf target-like work, ignore light fragments.
        if target.endswith("W") and Z < 64:
            continue

        with fn.open() as f:
            for line in f:
                parts = line.split()
                if len(parts) < 3:
                    continue
                try:
                    A = int(parts[0])
                    sigma_after = float(parts[2])
                except ValueError:
                    continue
                if sigma_after <= 0:
                    continue
                rows.append({
                    "target": target,
                    "source_file": str(fn),
                    "Z": Z,
                    "A": A,
                    "N": A - Z,
                    "sigma_after_mb": sigma_after,
                    "sigma_weighted_mb": sigma_after,
                })

    df = pd.DataFrame(rows)
    summed = df.groupby(["Z", "N", "A"], as_index=False)["sigma_weighted_mb"].sum().sort_values(["Z", "N", "A"])
    ensure_dir(out_rows.parent)
    df.to_csv(out_rows, index=False)
    summed.to_csv(out_summed, index=False)
    return df, summed


def build_kernel(case_folder: Path, fort_cfg: dict, out_csv: Path) -> pd.DataFrame:
    mapping, _, _ = read_fort15_mapping(case_folder / fort_cfg.get("fort15", "fort.15"))
    f_edist = case_folder / mapping.get(fort_cfg.get("edist_key", "edist"), "fort.21")
    f_scatlab = case_folder / mapping.get(fort_cfg.get("scatlab_key", "scatlab"), "fort.31")
    f_dsiglab = case_folder / mapping.get(fort_cfg.get("dsiglab_key", "dsiglab"), "fort.41")

    edist = parse_block_samples(f_edist)
    scatlab = parse_block_samples(f_scatlab)
    dsiglab = parse_block_samples(f_dsiglab)
    scatlab_lu = make_lookup(scatlab)
    dsiglab_lu = make_lookup(dsiglab)

    rows = []
    for s in edist.itertuples(index=False):
        key = (round(float(s.tkel_mev), 3), round(float(s.r_fm), 3))
        if key not in scatlab_lu or key not in dsiglab_lu:
            continue
        a = scatlab_lu[key]
        w = dsiglab_lu[key]
        rows.append({
            "tkel_mev": float(s.tkel_mev),
            "r_fm": float(s.r_fm),
            "theta_header_deg": float(s.theta_header_deg),
            "dsig_rdl_header": float(s.dsig_rdl_header),
            "edist_value": float(s.value),
            "theta_lab_partition_deg": float(a["value"]),
            "dsiglab_mb_per_mev_sr": float(w["value"]),
        })

    df = pd.DataFrame(rows).replace([np.inf, -np.inf], np.nan).dropna()
    df["edist_clip"] = df["edist_value"].clip(lower=0.0)
    df["dsiglab_clip"] = df["dsiglab_mb_per_mev_sr"].clip(lower=0.0)
    df["weight_hdr_edist"] = df["dsig_rdl_header"].clip(lower=0.0) * df["edist_clip"]
    df["weight_dsiglab"] = df["dsiglab_clip"]
    df["weight_combined"] = df["weight_hdr_edist"] * np.maximum(df["dsiglab_clip"], 1e-300)
    ensure_dir(out_csv.parent)
    df.to_csv(out_csv, index=False)
    return df


def filter_kernel(kernel_csv: Path, out_csv: Path) -> pd.DataFrame:
    df = pd.read_csv(kernel_csv)
    good = df[(df["edist_value"] > 0) & (df["theta_lab_partition_deg"] > 0) & (df["dsiglab_clip"] > 0)].copy()
    if good.empty:
        raise RuntimeError("No populated rows survived kernel filtering.")
    good.to_csv(out_csv, index=False)
    return good


def _local_halfwidth(values: np.ndarray, i: int, default_scale: float = 0.5) -> float:
    if len(values) <= 1:
        return default_scale
    vals = np.asarray(values, dtype=float)
    if i == 0:
        return 0.5 * abs(vals[1] - vals[0])
    if i == len(vals) - 1:
        return 0.5 * abs(vals[-1] - vals[-2])
    return 0.25 * abs(vals[i + 1] - vals[i - 1])


def build_recoil_from_kernel(filtered_csv: Path, cfg: dict, out_csv: Path) -> pd.DataFrame:
    rng = np.random.default_rng(int(cfg.get("random_seed", 12345)))
    df = pd.read_csv(filtered_csv).copy()
    reaction = cfg["reaction"]
    proj = reaction["projectile"]
    targ = reaction["target"]
    interest = cfg["interest"]
    recoil_A = int(interest["isotopes"][0])
    recoil_Z = int(interest["Z"])
    fort_cfg = cfg.get("fort", {})
    mode = cfg.get("mode", {}).get("recoil_reconstruction", "kernel_header")
    branch = fort_cfg.get("recoil_branch", "larger")

    ejectile_A = int(proj["A"] + targ["A"] - recoil_A)
    weight_col = fort_cfg.get("kernel_weight", "weight_hdr_edist")
    if weight_col not in df.columns:
        raise RuntimeError(f"Requested kernel weight column not present: {weight_col}")

    # Estimating local TKEL bin half-widths, grouped by trajectory block.
    df["tkel_halfwidth"] = np.nan
    for _, idx in df.groupby("r_fm").groups.items():
        sub = df.loc[list(idx)].sort_values("tkel_mev")
        vals = sub["tkel_mev"].to_numpy(float)
        hws = [_local_halfwidth(vals, i, default_scale=1.0) for i in range(len(vals))]
        df.loc[sub.index, "tkel_halfwidth"] = hws

    # Estimating local angular half-widths from the populated kernel rows.
    for ang_col in ["theta_header_deg", "theta_lab_partition_deg"]:
        sub = df.sort_values(ang_col)
        vals = sub[ang_col].to_numpy(float)
        hws = [_local_halfwidth(vals, i, default_scale=0.25) for i in range(len(vals))]
        df.loc[sub.index, ang_col + "_halfwidth"] = hws

    nsamp = int(fort_cfg.get("cell_samples", 25))
    use_uniform = bool(fort_cfg.get("cell_sample_uniform", True))

    rows = []
    for row in df.itertuples(index=False):
        cell_weight = float(getattr(row, weight_col))
        if cell_weight <= 0:
            continue

        if mode == "kernel_header":
            angle_center = float(row.theta_header_deg)
            angle_halfwidth = float(getattr(row, "theta_header_deg_halfwidth"))
            source_type = "theta_header_deg"
        elif mode == "kernel_partition":
            angle_center = float(row.theta_lab_partition_deg)
            angle_halfwidth = float(getattr(row, "theta_lab_partition_deg_halfwidth"))
            source_type = "theta_lab_partition_deg"
        else:
            raise RuntimeError(f"Unsupported recoil mode: {mode}")

        tkel_center = float(row.tkel_mev)
        tkel_halfwidth = float(getattr(row, "tkel_halfwidth"))

        angle_halfwidth = max(angle_halfwidth, 1e-6)
        tkel_halfwidth = max(tkel_halfwidth, 1e-6)

        # Sampling inside each populated kernel cell.
        if use_uniform:
            ang_samples = rng.uniform(angle_center - angle_halfwidth, angle_center + angle_halfwidth, nsamp)
            tkel_samples = rng.uniform(tkel_center - tkel_halfwidth, tkel_center + tkel_halfwidth, nsamp)
        else:
            ang_samples = rng.normal(angle_center, angle_halfwidth / np.sqrt(3.0), nsamp)
            tkel_samples = rng.normal(tkel_center, tkel_halfwidth / np.sqrt(3.0), nsamp)

        sample_weight = cell_weight / float(nsamp)
        for source_angle_deg, tkel_mev in zip(ang_samples, tkel_samples):
            th_rec, e_rec = reconstruct_from_header(
                theta_header_deg=float(source_angle_deg),
                tkel_mev=float(tkel_mev),
                projectile_A=int(proj["A"]),
                recoil_A=recoil_A,
                ejectile_A=ejectile_A,
                beam_energy_mevu=float(reaction["beam_energy_mevu"]),
                branch=branch,
            )
            if th_rec is None or e_rec is None or e_rec <= 0:
                continue
            rows.append({
                "tkel_mev": float(tkel_mev),
                "r_fm": float(row.r_fm),
                "source_angle_deg": float(source_angle_deg),
                "source_angle_type": source_type,
                "theta_header_deg": float(row.theta_header_deg),
                "theta_lab_partition_deg": float(row.theta_lab_partition_deg),
                "cell_weight": cell_weight,
                "weight": sample_weight,
                "theta_recoil_deg": th_rec,
                "e_recoil_mevu": e_rec,
                "recoil_A": recoil_A,
                "recoil_Z": recoil_Z,
                "target_A": int(targ["A"]),
                "target_Z": int(targ["Z"]),
            })

    out = pd.DataFrame(rows)
    if out.empty:
        raise RuntimeError("No recoil rows were produced from filtered kernel.")
    ensure_dir(out_csv.parent)
    out.to_csv(out_csv, index=False)
    return out


def command_run_case(args: argparse.Namespace) -> None:
    cfg = load_cfg(args.config)
    outdir = Path(cfg["paths"]["output_folder"]).expanduser()
    ensure_dir(outdir)

    reaction = cfg["reaction"]
    targ = reaction["target"]
    mode_cfg = cfg.get("mode", {})

    # If requested in YAML, run the evaporation calculation first.
    if mode_cfg.get("run_evaporation", False):
        run_dir = run_evaporation(cfg)
        rows_csv = outdir / f"{cfg['case_name']}_tlf_all_rows.csv"
        summed_csv = outdir / f"{cfg['case_name']}_tlf_summed.csv"
        build_afterevap_tables(Path(cfg["paths"]["auto_folder"]).expanduser(), f"{targ['A']}{targ['symbol']}", rows_csv, summed_csv)
        print(f"Evaporation run completed in {run_dir}")
        print(f"Wrote {rows_csv}")
        print(f"Wrote {summed_csv}")

    # These files are always built from the fort.* outputs for the case folder.
    case_folder = Path(cfg["paths"]["case_folder"]).expanduser()
    kernel_csv = outdir / f"{cfg['case_name']}_kernel.csv"
    filtered_csv = outdir / f"{cfg['case_name']}_kernel_filtered.csv"
    reco_csv = outdir / f"{cfg['case_name']}_reconstructed.csv"

    kernel = build_kernel(case_folder, cfg.get("fort", {}), kernel_csv)
    filtered = filter_kernel(kernel_csv, filtered_csv)
    reco = build_recoil_from_kernel(filtered_csv, cfg, reco_csv)
    print(f"Wrote {kernel_csv} ({len(kernel)} rows)")
    print(f"Wrote {filtered_csv} ({len(filtered)} rows)")
    print(f"Wrote {reco_csv} ({len(reco)} rows)")


def main() -> int:
    ap = argparse.ArgumentParser(description="GRAZING builder")
    sub = ap.add_subparsers(dest="cmd", required=True)
    p = sub.add_parser("run-case", help="Run one generic case from a YAML config")
    p.add_argument("--config", required=True)
    args = ap.parse_args()
    if args.cmd == "run-case":
        command_run_case(args)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
